### ISSUE TITLE
All files downloaded are 0 Bytes in size and have a unique file extension?

### ISSUE THREAD

**Issue by nodecentral** [Zebradil/Gimme-iPhotos#8] opened 2020-08-26 21:09 UTC
Hi

I managed to get it to work (well at least I think I did) but all the files It downloaded are 0 Bytes in size and have a unique file extension? E.g. 

IMG_2903.JPG.7qns8vy7
IMG_2904.JPG.b25jjiw6

Details from the command line..

Succeed
Downloading all photos into '/share/Public' while skipping existing…
Total:  46%|███████████████████████████████████████████████████████████████████████████████████▎                                                                                                | 901/1946 [00:41<02:53,  6.02it/s]Total: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1946/1946 [01:19<00:00, 24.38it/s]Downloaded: 1946 | Skipped: 0 | Overwritten: 0 | Total: 1946

**Comment by Zebradil** [comment] 2020-08-26 21:35
That looks like download stopped after creating temporary file.
Could you try using docker container — to eliminate environment-specific issues?

```sh
docker run -it \
    -v /share/Public:/dest \
    zebradil/gimme-iphotos -d /dest
```

Also, maybe it make sense changing destination `/share/Public` to something else, or cleanup it before running the aforementioned command.

**Comment by Zebradil** [comment] 2020-08-26 21:39
Also, to get more information about downloading, consider increasing verbosity by adding `-vvvv` to the command.

**Comment by nodecentral** [comment] 2020-08-26 21:46
Hi, thanks - I run it on my QNAP from the command line.

As for using a container- I’m not overly familiar with Docker and its command line, but putting that to one side - once installed, how do I run the actual gimme-iphotos download command ?

**Comment by Zebradil** [comment] 2020-08-26 22:26
In this case let's avoid messing with Docker for now (for some reason I thought that you're trying it on a casual Linux machine).
First, let's check python version: `python3 --version`.
Next, repeat the command you initially run, but with `-vvvv` to get more info.

**Comment by nodecentral** [comment] 2020-08-27 00:20
Hi

Interesting I don’t seem to have python3?

```
[~] # python --version                                 
Python 2.7.5
[~] # python3 --version
-sh: python3: command not found
[~] # 
```

**Comment by Zebradil** [comment] 2020-08-27 00:29
Yes, it could be the reason, for sure. Please, install python3 (`>=3.6`) and install gimme-iphotos via `pip3 install gimme-iphotos`.
Sorry, I'm not familiar with QNAP, so I can't give more precise advice here.

**Comment by Zebradil** [comment] 2020-09-08 09:12
Closing for now. Feel free to get back with more info and I'll try to provide any help I can.

**Comment by leendersf** [comment] 2021-03-26 09:34
Hello, I have the same situation here. And I try to use it in a Docker container but then I get this message:

> zebradil/gimme-iphotos -d /dest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error

**Comment by Zebradil** [comment] 2021-03-30 23:55
@leendersf 

Sorry, I got busy last days. The problem with the image is that you're running it on arm architecture (Rasperry PI, for example). I'll see if I can prepare multi-arch docker image.

Did you try to run gimme-iphotos without docker?

**Comment by leendersf** [comment] 2021-03-31 12:59
Hello, no problem. I tried it in Docker indeed. Haven’t tried it without.

**Comment by Zebradil** [comment] 2021-04-05 23:16
@leendersf I've built multiarch image. Please, try it out after `docker pull zebradil/gimme-iphotos`.

**Comment by leendersf** [comment] 2021-04-06 05:49
It works like a charm!! Thank you for the great work!!!!

**Comment by Zebradil** [comment] 2021-04-06 06:13
Thanks for testing, I didn't have time for that yesterday. Let me test run it now.

**Comment by Zebradil** [comment] 2021-04-06 20:59
Hm, I'm not able to reproduce this.
Here is how I run it:
```
docker run --rm -it -v /tmp/icloud:/icloud zebradil/gimme-iphotos -u design.ber@gmail.com -d /icloud
Enter iCloud password for design.ber@gmail.com:
Two-step authentication required.
Have you received authentication request on any of your devices? [y/N]: y
Please enter validation code: 018282
Succeed
Downloading all photos into '/icloud' while skipping existing…
Total:  18%|█████████████████▎                                                                            | 301/1631 [00:15<38:09,  1.72s/it^Total:  25%|███████████████████████                                                                       | 400/1631 [00:16<00:52, 23.53it/s]
Stopping tasks

Aborting.
```
And then 
```
l /tmp/icloud
.rw------- 1,7M root 25 Dec  2020 65BEE519-E324-4D32-8A92-A26AD2583E87.jpg
.rw------- 1,9M root  6 Jan 14:09 camphoto_824023566.jpg
.rw------- 1,3M root  9 Jan 15:55 IMG_0002.JPG
.rw------- 2,2M root  2 Jan 14:35 IMG_6669.HEIC
.rw------- 2,2M root  2 Jan 14:35 IMG_6670.HEIC
.rw------- 2,2M root  2 Jan 14:35 IMG_6671.HEIC
.rw------- 2,3M root  2 Jan 14:35 IMG_6672.HEIC
.rw------- 2,1M root  2 Jan 14:36 IMG_6673.HEIC
.rw------- 2,2M root  2 Jan 14:36 IMG_6674.HEIC
.rw------- 2,2M root  2 Jan 14:36 IMG_6675.HEIC
```

How exactly do you run it? Maybe there are some warnings or errors are showing up?

**Comment by leendersf** [comment] 2021-04-06 21:06
Hello thank you. I run it like this:

pi@raspberrypi:~ $ gimme-iphotos -u leenders.f@icloud.com 
Enter iCloud password for leenders.f@icloud.com: 
Destination is not set. Specify destination directory: Photos
Downloading all photos into '/home/pi/Photos' while skipping existing…
Total:   5%|█▍                             | 1399/29748 [01:23<07:08, 66.21it/s]
Total:  12%|███▋                           | 3594/29748 [04:07<08:20, 52.27it/s]

**Comment by Zebradil** [comment] 2021-04-06 21:17
1. Do you clean up the empty files before running the command?
2. Try running it via docker as I demonstrated above. I've built multiarch image especially to debug your case.

Running the package directly with python < 3.8 might not work. 3.8 is the oldest version I tested gimme-iphotos with. Not sure if I'll be able to add support for older versions, because it will take some time. Maybe it makes sense to update python.

**Comment by leendersf** [comment] 2021-04-06 21:21
But I don't understand the command:

docker run --rm -it -v /tmp/icloud:/icloud zebradil/gimme-iphotos -u design.ber@gmail.com -d /icloud

should I try:
docker run --rm -it -v /tmp/icloud:/icloud Photos -u something@icloud.com -d /icloud

My folder on the Raspberry is Photos. Sorry for my bad understanding..

**Comment by Zebradil** [comment] 2021-04-06 21:34
No worries, I'll break down the command:

```sh
docker run 
    --rm # delete container after it is completed
    -it # run interactively — to be able to login
    -v /tmp/icloud:/icloud # mount /tmp/icloud from host system to /icloud inside container
    zebradil/gimme-iphotos # specify which container image to run
      # here goes gimme-iphoto arguments
    -u design.ber@gmail.com # apple ID
    -d /icloud # where to download files inside container, 
               # it can be anything, but should match the directory in -v argument
```
In your case the command might look like the following:
```sh
docker run --rm -it -v $PWD/Photos:/foo zebradil/gimme-iphotos -u something@icloud.com -d /foo
```
So, `$PWD/Photos` can be replaced by absolute path to the directory, like `/home/something/Photos`.

**Comment by leendersf** [comment] 2021-04-06 21:40
Zebradil: I thank you for your patience but:

You are a hero! The photo's are floating in my folder!!!!!! Thank you very much!

**Comment by Zebradil** [comment] 2021-04-06 21:44
You're welcome! :)

**Closed by Zebradil** 2021-04-06 21:44 UTC
Labels: bug, need more info
